# Generated by Django 5.2.7 on 2025-10-14 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_scholarshipapplication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('document_verified', 'Document Vérifié'), ('document_rejected', 'Document Rejeté'), ('application_approved', 'Demande Approuvée'), ('application_rejected', 'Demande Rejetée'), ('application_under_review', 'Demande en Examen'), ('system_alert', 'Alerte Système'), ('deadline_reminder', 'Rappel Date Limite'), ('info_request', "Demande d'Information")], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.scholarshipapplication')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentdocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Étudiant',
                'verbose_name_plural': 'Notifications Étudiant',
                'ordering': ['-created_at'],
            },
        ),
    ]
