# Generated by Django 5.2.7 on 2025-10-15 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
