# Generated by Django 5.2.7 on 2025-10-15 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnotification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
